name: uniwm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
      # Base UniWM environment only.
      
      # Habitat is managed separately via:
      #   - envs/uniwm-habitat025-addons.yml
      #   - envs/uniwm-habitat025-pip.txt
      #   - scripts/setup_habitat025_uniwm.sh

      # flash-attn is installed separately via:
      #   - conda install -c nvidia cuda
      #   - pip install flash-attn==2.5.9.post1 --no-build-isolation
      - torch==2.4.0
      - torchvision==0.19.0
      - torchaudio==2.4.0
      - torchmetrics==1.2.0
      - torch-fidelity==0.3.0
      - pytorch-msssim==1.0.0
      - accelerate==0.33.0
      - datasets==2.20.0
      - deepspeed==0.15.0
      - distributed==2023.4.1
      - dreamsim==0.2.1
      - einops==0.8.0
      - evaluate==0.4.2
      - evo==1.31.1
      - lpips==0.1.4
      - ninja==1.11.1.1
      - numpy==1.24.3
      - packaging==24.1
      - peft==0.12.0
      - pillow==10.4.0
      - pyyaml==6.0.1
      - requests==2.32.2
      - sentencepiece==0.2.0
      - tqdm==4.66.4
      - transformers @ git+https://github.com/leloykun/transformers.git@dae439cb93e7c2ef61943554b7a2f4590c2118cd
      - wandb==0.17.4
